### ISSUE TITLE
Backing up acme certs and making persistent

### ISSUE THREAD

**Issue by joshuacox** [rawmind0/alpine-traefik#31]
So I have hit the dreaded:

```
Error 429 - urn:acme:error:rateLimited - Error creating new cert :: too many certificates already issued for exact set of domains:
```

Because I have restart traefik too many times this week on a few of my domains.  So I decided to dig in and find the certs.  @rawmind0 please correct me if I'm mistaken on any of this.  But it looks like all the certs are stored in `acme.json` which is in the `/opt/traefik/acme` directory.

My question is can I volume mount in this directory?  Perhaps using convoy-NFS?  I'm going to give it a shot, but I'd welcome any comments or suggestions?

[here's](https://github.com/rawmind0/service-catalog/pull/3) an example in PR form, feel free to reject.  I'm going to test this out on a test environment.

**Comment by joshuacox** [comment]
ok the `v1.2.3-rancher1-8` is a working version, I had a few issues along the way that I think were unrelated to traefik ( i had an old environment in which health checks had started misbehaving amongst a few other issues). After creating a fresh envrionment this seems to be working now, testing further.  I'd welcome any comments or suggestions.

**Comment by joshuacox** [comment]
@rawmind0 do you think it will be all right if I am just mounting in the `/opt/traefik/acme` directory as a volume?  

And if that is all right, what do you think about it being shared to many alpine traefik containers spawned on many front-end hosts with public IP addresses talking to various clustered services in the backend?

I think the obvious first worry is multiple instances trying to open the acme.json at once.

Right now I'm getting pretty good results.  i.e. I've got enforced SSL on a domain, and restarting the container does not get me rate-limit banned at letsencrypt.

**Comment by mcnilz** [comment]
``/opt/traefik/acme`` should be a volume. I ran into rate-limit after upgrading to v1.2.3-rancher1

**Comment by rawmind0** [comment]
Hey @joshuacox ...
Obviously, to use traefik with acme enabled in production, a better persistence solution for ssl certs is needed. 

Sharing `/opt/traefik/acme` doesn't seem a good idea, due to traefik need write access to acme.json and the file will get corrupted, eventually. IMHO, bad direction.

At this point, i see two ways, use a shared volume or distributed key/value: 
- one would be try to connect traefik to a distributed key/value and configure it in HA mode `https://docs.traefik.io/user-guide/kv-config/`
- another would be use the @janeczku letsencrypt rancher integration and use it with traefik instead the built-in acme integration.

What do you think??

**Comment by joshuacox** [comment]
@rawmind0 I kind of like the idea of using the kv store,  your choice on which one consul, etcd, zookeper, boltdb.  I've got more experience with etcd and consul, but I'm open to the other two as well.

@mcnilz I have a fork with a branch [here](https://github.com/joshuacox/service-catalog/tree/persistentAcme) that can be added to a rancher and you can have `/opt/traefik/acme` as a volume.

I'd love feedback of any sort as I'm already using this method in a 'production' instance, for better or worse (much better now that I have acme.json persistent and not hitting the rate limits).

**Comment by rawmind0** [comment]
@joshuacox , which kv store is not a problem, which ever could work just fine... I guess that all are already on the rancher community catalog... :)

I've took a look at [your-catalog](https://github.com/joshuacox/service-catalog/tree/persistentAcme) and i think that it shouldn't work. Don't you have file permission issues?? Due to traefik is running with user `traefik` UID `10001` and volume should be root owned.... 

Anyway, just as advice, don't add the volume directly to the traefik container, is a bad practice. I think is much better provide the volume through another container and add it to traefik volumes_from section.... ;) 

Code for traefik.....(also add `traefik-acme` to traefik volumes_from section)
```
traefik-acme:
  net: none
  labels:
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  environment:
    - SERVICE_UID=10001
    - SERVICE_GID=10001
    - SERVICE_VOLUME=/opt/traefik/acme
  volumes:
    - /opt/traefik/acme
  volume_driver: ${VOLUME_DRIVER}
  image: rawmind/alpine-volume:0.0.2-1
```

rawmind/alpine-volume, is a container just to do this kind of thinks easily. It creates the volume and set `$SERVICE_UID` as owner....
