### ISSUE TITLE
Traefik stays "initializing"

### ISSUE THREAD

**Issue by Hermsi1337** [rawmind0/alpine-traefik#55]
Hey,

I somehow can't manage to get Traefik working along with rancher.
As soon as I start Traefik, the service keeps in "Initializing"-state in rancher. (Check below for .yml-files)

I would really appreciate some help since I do not seem to understand the docs properly..^^
I grepped the labels from this documentation: https://docs.traefik.io/configuration/backends/rancher/

Interestingly, I am able to reach the Traefik Admin-Panel and inspect my containers and their rules.

I'm basically using three hosts. One Host with rancher-service and two "application"-hosts for everything else. Traefik ist supposed to boot on one host only.

Thank you in advance.

Regards,
Hermsi

Traefik docker-compose.yml:
```yml
version: '2'
volumes:
  $${acme_vol_name}:
    driver: local
services:
  traefik:
    image: rawmind/alpine-traefik:1.4.0-3
    environment:
      CATTLE_ACCESS_KEY: SECRET
      CATTLE_SECRET_KEY: SUPERSECRET
      CATTLE_URL: https://rancher.mydomain.de/v1/projects/1a5
      TRAEFIK_ACME_CASERVER: '"https://acme-v01.api.letsencrypt.org/directory"'
      TRAEFIK_ACME_EMAIL: info@mydomain.com
      TRAEFIK_ACME_ENABLE: 'true'
      TRAEFIK_ACME_ONDEMAND: 'true'
      TRAEFIK_ACME_ONHOSTRULE: 'true'
      TRAEFIK_ADMIN_AUTH_METHOD: basic
      TRAEFIK_ADMIN_AUTH_USERS: lmao:$$apr1$$ahHVnXh/$$rpduzZZupOQ7/6KJ/mn0L.
      TRAEFIK_ADMIN_ENABLE: 'true'
      TRAEFIK_ADMIN_READ_ONLY: 'false'
      TRAEFIK_ADMIN_STATISTICS: '10'
      TRAEFIK_HTTPS_COMPRESSION: 'true'
      TRAEFIK_HTTPS_ENABLE: 'true'
      TRAEFIK_HTTPS_PORT: '8443'
      TRAEFIK_HTTP_COMPRESSION: 'true'
      TRAEFIK_HTTP_PORT: '8080'
      TRAEFIK_INSECURE_SKIP: 'false'
      TRAEFIK_RANCHER_ENABLE: 'true'
      TRAEFIK_RANCHER_MODE: api
    volumes_from:
    - traefik-acme
    ports:
    - 8000:8000/tcp
    - 8080:8080/tcp
    - 8443:8443/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: traefik_lb=true
      io.rancher.sidekicks: traefik-acme
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.scheduler.global: 'true'
  traefik-acme:
    image: rawmind/alpine-volume:0.0.2-1
    environment:
      SERVICE_GID: '10001'
      SERVICE_UID: '10001'
      SERVICE_VOLUME: /opt/traefik/acme
    network_mode: none
    volumes:
    - traefik_acme_vol:/opt/traefik/acme
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
```

rancher-compose.yml
```yml
version: '2'
services:
  traefik:
    metadata:
      traefik: &id001
        ssl_crt: |2+

        ssl_key: |2+

    retain_ip: true
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 5000
      port: 8000
      unhealthy_threshold: 3
      interval: 5000
      strategy: recreate
  traefik-acme:
    metadata:
      traefik: *id001
    retain_ip: true
    scale: 1
    start_on_create: true
```

And thats my whoami-service for testing...
docker-compose.yml:
```yml
version: '2'
services:
  whois:
    image: jwilder/whoami
    stdin_open: true
    tty: true
    labels:
      traefik.frontend.rule: Host:whoami.hermsi.de
      traefik.enable: 'true'
      io.rancher.container.pull_image: always
      traefik.frontend.entryPoints: http,https
```

rancher-compose.yml
```
version: '2'
services:
  whois:
    scale: 1
    start_on_create: true
```
