### ISSUE TITLE
HA-Clustering Traefik on multiple Hosts

### ISSUE THREAD

**Issue by Hermsi1337** [rawmind0/alpine-traefik#56]
Good evening @rawmind0 

it's me again. I would be very happy if your are gracious enough to help me for the second time.

I'm currently struggling with setting up Traefik on two hosts:
![unbenannt](https://user-images.githubusercontent.com/16942003/31865587-5988d5b8-b771-11e7-8874-5f4befe34efd.JPG)

My Setup looks like the following:
* Two Hosts with label `traefik_lb=true` and Traefik running on them. For config see [1]
* A webtest-stack bootet on every hosts. For config see [2]
* My domain with two a-records pointing to both hosts and using round robin dns
![unbenannt](https://user-images.githubusercontent.com/16942003/31865668-ca81b9fa-b772-11e7-85d1-8b08b6dda0d7.JPG)

When I login into traefik admin-panel I see my frontend along with the corresponding backend:
![unbenannt](https://user-images.githubusercontent.com/16942003/31865688-0803183c-b773-11e7-9723-4d3bf183254d.JPG)

But as soon as I visit the Frontend - no matter which server - I'm facing a `404 page not found`-error.

Is it even possible to achieve this setup using Traefik? Am I missing an important detail?
I did a lot of research but I didn't find the thing I'm missing in this case.

Thanks a lot for your help!

Traefik-configuration [1]
docker-compose.yml:
```yml
version: '2'
volumes:
  $${acme_vol_name}:
    driver: local
services:
  traefik:
    image: rawmind/alpine-traefik:1.4.0-3
    environment:
      CATTLE_ACCESS_KEY: SECRET
      CATTLE_SECRET_KEY: SECRET AF
      CATTLE_URL: https://rancher.domain.de/v1/projects/1a5
      TRAEFIK_ACME_CASERVER: '"https://acme-v01.api.letsencrypt.org/directory"'
      TRAEFIK_ACME_EMAIL: info@domain.com
      TRAEFIK_ACME_ENABLE: 'true'
      TRAEFIK_ACME_ONDEMAND: 'true'
      TRAEFIK_ACME_ONHOSTRULE: 'true'
      TRAEFIK_ADMIN_AUTH_METHOD: basic
      TRAEFIK_ADMIN_AUTH_USERS: user:$$apr1$$ahHVnXh/$$rpduzZZupOQ7/6KJ/mn0L.
      TRAEFIK_ADMIN_ENABLE: 'true'
      TRAEFIK_ADMIN_READ_ONLY: 'false'
      TRAEFIK_ADMIN_STATISTICS: '10'
      TRAEFIK_HTTPS_COMPRESSION: 'true'
      TRAEFIK_HTTPS_ENABLE: only
      TRAEFIK_HTTPS_PORT: '443'
      TRAEFIK_HTTP_COMPRESSION: 'true'
      TRAEFIK_HTTP_PORT: '80'
      TRAEFIK_INSECURE_SKIP: 'false'
      TRAEFIK_RANCHER_ENABLE: 'true'
      TRAEFIK_RANCHER_MODE: api
      LOGLEVEL: DEBUG
    volumes_from:
    - traefik-acme
    ports:
    - 8000:8000/tcp
    - 80:80/tcp
    - 443:443/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: traefik_lb=true
      io.rancher.sidekicks: traefik-acme
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.global: 'true'
  traefik-acme:
    image: rawmind/alpine-volume:0.0.2-1
    environment:
      SERVICE_GID: '10001'
      SERVICE_UID: '10001'
      SERVICE_VOLUME: /opt/traefik/acme
    network_mode: none
    volumes:
    - traefik_acme_vol:/opt/traefik/acme
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
```
rancher-compose.yml: 
```yml
version: '2'
services:
  traefik:
    metadata:
      traefik: &id001
        ssl_crt: ''
        ssl_key: ''
    retain_ip: true
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 5000
      port: 8000
      unhealthy_threshold: 3
      interval: 5000
      strategy: recreate
  traefik-acme:
    metadata:
      traefik: *id001
    retain_ip: true
    scale: 1
    start_on_create: true
```

webtest-configuration [2]
docker-compose.yml:
```yml
version: '2'
services:
  test:
    image: rawmind/web-test
    stdin_open: true
    tty: true
    labels:
      traefik.frontend.rule: Host:dev.domain.de
      traefik.enable: 'true'
      traefik.port: '8080'
      traefik.domain: dev.domain.de
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
      traefik.frontend.entryPoints: http, https
```

rancher-compose.yml:
```yml
version: '2'
services:
  test:
    start_on_create: true
```
