### ISSUE TITLE
Services unreachable after service restart

### ISSUE THREAD

**Issue by khusseini** [rawmind0/alpine-traefik#58]
Hello,

some of my services remain unreachable after I restart them, however once I manually restart traefik things work again.

Here are my composer files

docker-compose.yml
```yaml
version: '2'
volumes:
  tools-volume:
    driver: local
    per_container: true
  $$$${VOLUME_NAME}:
    driver: rancher-nfs
services:
  traefik-conf:
    image: rawmind/rancher-traefik:1.3.6
    network_mode: none
    volumes:
    - tools-volume:/opt/tools
    labels:
      io.rancher.scheduler.affinity:host_label: traefik_lb=true
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  traefik:
    image: rawmind/alpine-traefik:1.4.0-3
    environment:
      CATTLE_ACCESS_KEY: *snip*
      CATTLE_SECRET_KEY: *snip*
      CATTLE_URL: *snip*
      CONF_INTERVAL: '10'
      TRAEFIK_ACME_CASERVER: '"https://acme-v01.api.letsencrypt.org/directory"'
      TRAEFIK_ACME_EMAIL: *snip*
      TRAEFIK_ACME_ENABLE: 'true'
      TRAEFIK_ACME_ONDEMAND: 'true'
      TRAEFIK_ADMIN_ENABLE: 'true'
      TRAEFIK_HTTPS_ENABLE: 'true'
      TRAEFIK_HTTPS_PORT: '443'
      TRAEFIK_HTTP_PORT: '80'
      TRAEFIK_RANCHER_ENABLE: 'true'
      TRAEFIK_DEBUG: 'true'
      TRAEFIK_RANCHER_DOMAIN: *snip*
    volumes_from:
    - traefik-conf
    - traefik-acme
    ports:
    - 80:80/tcp
    - 443:443/tcp
    - 8000:8000/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: traefik_lb=true
      io.rancher.sidekicks: traefik-conf,traefik-acme
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.global: 'true'
  traefik-acme:
    image: rawmind/alpine-volume:0.0.2-1
    environment:
      SERVICE_GID: '10001'
      SERVICE_UID: '10001'
      SERVICE_VOLUME: /opt/traefik/acme
    network_mode: none
    volumes:
    - TRAEFIK:/opt/traefik/acme
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
```

rancher-compose.yml
```yaml
version: '2'
services:
  traefik-conf:
    metadata:
      traefik: &id001
        ssl_crt: ''
        ssl_key: ''
    retain_ip: true
    scale: 1
    start_on_create: true
  traefik:
    metadata:
      traefik: *id001
    retain_ip: true
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 80
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
  traefik-acme:
    metadata:
      traefik: *id001
    retain_ip: true
    scale: 1
    start_on_create: true
```
Best regards
