### ISSUE TITLE
What I'm missing?

### ISSUE THREAD

**Issue by MichelDiz** [rawmind0/alpine-traefik#61]
Follows issue video. Do not worry about the information contained. IP is dynamic and so on. Everything changes there nothing is definitive. It's on a Google Cloud machine. I show all settings in the video.

Cheers 

https://youtu.be/ofSypJF-Gpk

```yml

version: '2'
services:
  traefik:
    privileged: true
    image: rawmind/alpine-traefik:1.4.0-3
    environment:
      TRAEFIK_ADMIN_AUTH_METHOD: digest
      TRAEFIK_ADMIN_AUTH_USERS: ''
      TRAEFIK_ADMIN_ENABLE: 'true'
      TRAEFIK_ADMIN_READ_ONLY: 'false'
      TRAEFIK_ADMIN_STATISTICS: '10'
      TRAEFIK_HTTPS_COMPRESSION: 'true'
      TRAEFIK_HTTPS_ENABLE: 'false'
      TRAEFIK_HTTPS_PORT: '443'
      TRAEFIK_HTTP_COMPRESSION: 'true'
      TRAEFIK_HTTP_PORT: '80'
      TRAEFIK_INSECURE_SKIP: 'false'
      TRAEFIK_RANCHER_ENABLE: 'true'
      TRAEFIK_RANCHER_MODE: metadata
      TRAEFIK_DEBUG: 'true'
      TRAEFIK_RANCHER_DOMAIN: umover.com.br
    ports:
    - 8000:8000/tcp
    - 80:80/tcp
    - 443:443/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: traefik_lb=true
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.global: 'true'

```
```yml

version: '2'
services:
  traefik:
    metadata:
      traefik:
        ssl_crt: ''
        ssl_key: ''
    retain_ip: true
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 5000
      port: 8000
      unhealthy_threshold: 3
      interval: 5000
      strategy: recreate

```
